### ISSUE TITLE
Fix "Imager has a new version available" pop-up at startup

### ISSUE THREAD

**Issue by AlexandraTrifan** [analogdevicesinc/adi-kuiper-imager#14]
Initially, the imager version was 1.6.2 - aligned with the rpi-imager. Since this is the Kuiper Imager, the initial version should be 1.0.0. 
This change added a issue at startup, where a pop-up appears to inform the user that a new version is available - this is based on a hardcoded information about the v1.6.2.

**Comment by tagoylo** [comment]
In macOS and Ubuntu, this does not appear anymore. Unable to check on Windows for now.
