### ISSUE TITLE
ToF images write exceed 100%, download corrupt hash does not match

### ISSUE THREAD

**Issue by jpineda3** [analogdevicesinc/adi-kuiper-imager#17]
**Environment:**
OS: Windows 10
SW Version: v1.0.0-rc1 https://github.com/analogdevicesinc/adi-kuiper-imager/commit/217014db6e60b4a75bb6ddb68a1381387bb021e3

**Describe the bug:**
Writing any ToF image exceeds 100% and ends up with Error "Download corrupt. Hash does not match." SD card is inaccessible after failure.

![writing_morethan_100](https://user-images.githubusercontent.com/76926625/201814303-4bc7cf49-5f2f-4cab-8ca6-4a55ba318ba1.png)
![tof_hash](https://user-images.githubusercontent.com/76926625/201812830-7e5d1ee0-1dbb-4560-8608-0c0914103180.png)

**Steps to reproduce:**
Write any ToF Image to SD card. Notice how writing exceeds 100% and eventually pop-up will appear.

**Expected behavior:**
Writing should complete at 100% then proceed to Verifying. Write Successful pop-up should appear if the image was properly etched on the SD card.

**Comment by jpineda3** [comment]
I also used a local file I downloaded from http://swdownloads.analog.com/cse/aditof/jetson_nano-latest-image.tar.xz.
For this case, Writing did not exceed 100% but an Error showed up "Unable to prepare for image customization."

The SD is not accessible after that error.

![tof_custom_unable_to_prepare_customization](https://user-images.githubusercontent.com/76926625/202111111-1aa074f5-02af-42fb-86ba-b9178a2e9ee9.png)

**Comment by AlexandraTrifan** [comment]
Fixed ToF JSON files, hash and size so that it does not exceed 100%.

**Comment by jpineda3** [comment]
Verified resolved.
