### ISSUE TITLE
[Enhancement] A warning or prompt must appear if the selected project is not supported in SD card

### ISSUE THREAD

**Issue by HRosete** [analogdevicesinc/adi-kuiper-imager#19]
**Environment:**
 - OS: Windows 10
 - SW Version or git tag: 217014d

**Describe the bug**
Kuiper Imager says that it successfully configured the zynq-coraz7s-cn0501 project from the ADI Kuiper Image 07/28 release even if it is not supported in that release (as seen in the picture; the picture shows a part of the list of projects supported in the 07/28 release wherein zynq-coraz7s-cn0501 is not supported)

**To Reproduce**
1. Click on "Storage (Unconfigured)" and select the storage device.
2. Click on "Image Source (Unconfigured)" >> "ADI Kuiper Linux" >> "ADI Kuiper Linux (32 bit), 07/28 release date"
3. "Write"
4. Wait
5. Configure content for Xilinx >> zynq >> coraz7s >> cn0501.
6. "ADI Kuiper Imager Configured it successfully" even though the project is not supported on the 07/28 release.

**Expected behavior**
There are 2 possible scenarios for this:
1. The unsupported project for the specific release must be grayed out.
2. The pop-up modal that says "ADI Kuiper Imager configured it successfully" must indicate a warning that says the project selected is not supported for the release. Or it mustn't say that it was successfully configured.

**Screenshots**
![image](https://user-images.githubusercontent.com/43806793/201873598-2173c293-6084-4486-9dac-a2dff0d3e2ab.png)

@tagoylo

**Comment by tagoylo** [comment]
Also, to add, as per checking with the kuiper.json [here](https://swdownloads.analog.com/cse/kuiper/imager/kuiper.json) for 7-28 image, there are projects that are defined as part of the boot partition but they are not really supported by the image version, this might be what's causing this issue.

**Comment by AlexandraTrifan** [comment]
JSON file on swdownloads for the 7-28 version seems to be broken and needs to be replaced with the correct one.

**Comment by AlexandraTrifan** [comment]
Updated the wrong JSON files. Projects and release versions should match now.

**Comment by tagoylo** [comment]
As per checking on the 2021R1 image Kuiper json and project list, they are matched now. This item can be closed.
