### ISSUE TITLE
Building Imager from Code: Update README.md

### ISSUE THREAD

**Issue by HRosete** [analogdevicesinc/adi-kuiper-imager#20]
## **Environment:**
 - OS: Ubuntu 22.04
 - SW Version or git tag: 217014d

## **Describe the bug**
Tried to build adi-kuiper-imager's master on Ubuntu 22.04 by following the instructions on README.md. While installing the dependencies, this error appeared:

`E: Package 'qt5-default' has no installation candidate`

To continue building, this library is bypassed by eliminating it from the list to be installed. I'm afraid this library is being used for the GUI, I'd like to ask if the README file must be updated.

## **To Reproduce**
1. Install the [dependencies](https://github.com/analogdevicesinc/adi-kuiper-imager#get-dependencies) for adi-kuiper-imager from the instruction in the README file

## **Expected behavior**
The installation must be smooth.

## **Logs**
[installing-kuiper-imager-dependencies.txt](https://github.com/analogdevicesinc/adi-kuiper-imager/files/10011216/installing-kuiper-imager-dependencies.txt)

**Comment by kimpaller** [comment]
Using package `qtbase5-dev` instead of `qt5-default` solved the problem. Ok to close the issue now.
