### ISSUE TITLE
Installation: Installing artifact for Ubuntu (v. 22.04) raises an error that needs to be handled

### ISSUE THREAD

**Issue by HRosete** [analogdevicesinc/adi-kuiper-imager#21]
## **Environment:**
 - OS: Ubuntu 22.04
 - SW Version or git tag: 217014d

## **Describe the bug**
Installed adi-kuiper-imager on an Ubuntu 22.04 machine using the artifact from the [v1.0.0-rc1](https://github.com/analogdevicesinc/adi-kuiper-imager/tree/v1.0.0-rc1) release raised this error:

`The following packages have unmet dependencies:`
`  kuiper-imager : Depends: libssl1.1 (>= 1.1.0) but it is not installable`
`E: Unable to correct problems, you have held broken packages.
`

Apparently, this issue is prominent in the Ubuntu community and has to do with the dotnet support on Ubuntu 22.04 (please see this [link](https://github.com/dotnet/core/issues/7038)). The GitHub thread led to this specific [workaround](https://github.com/MicrosoftDocs/live-share/issues/4646#issuecomment-1211442899) that worked for the machine. This enabled the installation of the artifact to be successful.

## **To Reproduce**
1. Install the artifact for Ubuntu on a Linux machine.
2. See the error.

## **Expected behavior**
This must be indicated in the README file. The installation must be smooth.

**Comment by tagoylo** [comment]
Installation on Ubuntu is successful after following README file. Issue can be closed.
