### ISSUE TITLE
ADI Kuiper Linux 2022-02-02 image version inconsistencies

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/adi-kuiper-imager#22]
**Environment:**

OS: Windows 10
SW Version: v1.0.0-rc1 https://github.com/analogdevicesinc/adi-kuiper-imager/commit/217014db6e60b4a75bb6ddb68a1381387bb021e3

**Describe the bug:**
After writing the image and then checking /BOOT, it can be observed that the supposed to be subfolders are available inside /BOOT. See picture. Some of the subfolders are in the red box.
![image](https://user-images.githubusercontent.com/25096080/201926207-e7664d65-07b6-4c95-832d-d18c2c29f0ab.png)

Also, this image seems to be not part of the released Kuiper images based on wiki analog: https://wiki.analog.com/resources/tools-software/linux-software/adi-kuiper_images/release_notes. 

**Steps to reproduce:**
1. Select ADI Kuiper Linux image released 2022-02-02
2. Write to SD card, wait
3. After the process, check /BOOT
4. Observe that the subfolders are also in /BOOT, they are only supposed to be inside their respective project folder

**Expected behavior:**
Kuiper images listed should be the ones that are released.

**Comment by SRaus** [comment]
I'm thinking that maybe 2022-02-02 image had a general problem with boot files. 
Could you please write the same image with other etcher (win32 imager, balena etcher, dd etc) and check if sub-folders still appear in /boot?

**Comment by tagoylo** [comment]
I've tried writing the same image (2022-02-02) using balena etcher and the same issue is also observed, sub-folders appear in/boot,

**Comment by SRaus** [comment]
This means that the problem is on the image side. 
I don't even know what that image is - actually it cannot be found on our internal server (Artifactory) so maybe it was something built just to test Imager.

**Comment by AlexandraTrifan** [comment]
Removed this image. It was just used for testing purposes during development.

**Comment by tagoylo** [comment]
ADI Kuiper Linux image released 2022-02-02 verified not on the list of OS. Only 2021 R1 image now appears on the list. Closing this issue.
