### ISSUE TITLE
Selecting 'ERASE' from the IMAGE SOURCE when SD CARD is WRITE PROTECTED and unconfigured.

### ISSUE THREAD

**Issue by cseptimo** [analogdevicesinc/adi-kuiper-imager#25]
**Environment:**
OS: Windows 10
SW Version: v1.0.0-rc1 https://github.com/analogdevicesinc/adi-kuiper-imager/commit/217014db6e60b4a75bb6ddb68a1381387bb021e3

**Describe the bug:**
The SD card is set to WRITE PROTECTED, the IMAGE SOURCE is visible and clickable even if the STORAGE is unconfigured, then it 
allows to select from the image source, from the selection, click 'erase'. Write button is visible but does not write/do its function.

**Steps to reproduce:**
1. The SD card should be in WRITE PROTECTED/lock.
2. Select STORAGE, then select the WRITE PROTECTED SD card.
3. Click 'continue' or 'X' in the error prompt saying that the SD card is locked. 
4. Then click IMAGE SOURCE
5. Select 'Erase' from the Image source selection.
6. Click 'Write' button

**Expected behavior:**
When the SD card is WRITE PROTECTED, the STORAGE is unconfigured. IMAGE SOURCE and 'WRITE' button should be grayed out and disabled/not clickable.

**Screenshot:**
![b3b3668a-68e4-4f0b-a611-0072dd227a97](https://user-images.githubusercontent.com/114046109/202069873-9c03a50c-ff9d-4c80-bbd8-51668e71bed6.jpg)

**Comment by AlexandraTrifan** [comment]
A fix was added and will be available in RC2

**Comment by cseptimo** [comment]
RC3 - Ubuntu 22.04
Item closed. Storage is empty when SD card is protected.
