### ISSUE TITLE
Storage: Ejecting the selected SD Card does not automatically update on the imager

### ISSUE THREAD

**Issue by HRosete** [analogdevicesinc/adi-kuiper-imager#26]
## **Environment**
- OS: Ubuntu 22.04, Windows 10, 11
- SW Version or git tag: 217014d

## **Describe the bug**
Ejecting the selected SD Card or any other storage device does not automatically update on the imager. Please see the screenshots below. It still functions as an imager with a properly selected SD card would: it can even "Erase" the said phantom SD Card (only applicable on Windows).

## **To Reproduce**
1. Plug an SD card on your machine and select it as the storage to be configured in the Kuiper Imager.
2. Eject the SD card, observe the imager.

## **Screenshots**
The SD Card is now ejected...
![Screenshot from 2022-11-16 11-05-59](https://user-images.githubusercontent.com/43806793/202073907-6ff3d7e0-346f-4ba8-b23f-7811c65a2244.png)

...and it still shows in the imager's storage.
![image](https://user-images.githubusercontent.com/43806793/202073956-08e23bc2-2b75-4d06-bb67-83b0ee187d6f.png)

I can even choose to "erase" the contents of the SD Card:
![image](https://user-images.githubusercontent.com/43806793/202074706-0e71eaed-cc90-4444-b0af-37929c3fc243.png)
![image](https://user-images.githubusercontent.com/43806793/202074751-ce9d227e-e4d5-44eb-8bb1-caa9f6cf05f4.png)

**Comment by AlexandraTrifan** [comment]
A mechanism was added to check periodically for the selected storage. If the mechanism detects that the storage was disconnected, it will automatically change the storage button to a different state. Will be available in RC2

**Comment by cseptimo** [comment]
Storage device can automatically detect whether the SD card is available, unavailable or ejected. This is fixed in RC2, checked it on Linux. Closing this item.
