### ISSUE TITLE
Kuiper's Target: Empty list of projects for RPI3, RPI3B, and RPI4

### ISSUE THREAD

**Issue by HRosete** [analogdevicesinc/adi-kuiper-imager#27]
## **Environment**
- OS: Ubuntu 22.04, Windows 10, 11
- SW Version or git tag: 217014d

## **Describe the bug/ future feature**
I selected ADI Kuiper Linux as my Image Source and proceeded to configure my target for RPI3 and saw that the list of projects is empty. This also holds true for the list of projects for RPI3B and RPI4.

I believe that it isn't supported in this release, but I'm logging this issue for future reference.

## **To Reproduce**
1. Plug an SD card on your machine and select it as the storage to be configured in the Kuiper Imager.
2. Click "Image Source (Unconfigured)".
3. Select "ADI Kuiper Linux" >> "ADI Kuiper Linux (32-bit)" (from any release).
4. On "Target (Unconfigured)" select the following: "rpi" >> "arm64" >> "rpi3" / "rpi3b" / "rpi4"

## **Screenshots**
![image](https://user-images.githubusercontent.com/43806793/202078363-bca8e99f-4d59-4bbe-bc48-d65d83ffe133.png)
![image](https://user-images.githubusercontent.com/43806793/202078429-8813ff33-03c4-4b52-b5cc-cbeefb1b146c.png)

**Comment by AlexandraTrifan** [comment]
A README was added under each RPI configuration to inform the user on how to manually add overlays.

**Comment by tagoylo** [comment]
Verified that there is a README available when navigating RPI projects. Issue can be closed.
