### ISSUE TITLE
Kuiper.json defined in kuiper os_list has inconsistencies

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/adi-kuiper-imager#28]
**Environment:**

OS: Windows 10
SW Version: v1.0.0-rc1 https://github.com/analogdevicesinc/adi-kuiper-imager/commit/217014db6e60b4a75bb6ddb68a1381387bb021e3

**Describe the bug:**
The main feature that is affected by the inconsistencies is the Configure Existing Content. When switching bootfiles some files are not copied. And by checking the kuiper.json found [here](https://swdownloads.analog.com/cse/kuiper/imager/kuiper.json) for 7-28 image and [here](https://swdownloads.analog.com/cse/kuiper/imager/kuiper_2022-2-2.json) for 2-22 image, here are the inconsistencies found:

1. Duplicate project entries. The following projects have duplicate entries: zcu102-fmcomms8, zcu102-daq3, zc706-ad9265_fmc, zc706-adrv9375. This will confuse user, since in Kuiper Imager, it will also show 2 of these on the list.
<img src="https://user-images.githubusercontent.com/25096080/202091361-24c30fe8-3550-48d3-8313-6cd5f2c41e7b.png" width=50% height=50%>

3. Wrong path for Image kernel file for zynqmp projects. In kuiper.json path for zynqmp kernel is "kernel": "zynqmp-common/uImage". It should be "kernel": "zynqmp-common/Image". This results to Image file not being copied to /BOOT.

4. versal-vck190-reva-ad9081 was not defined but it exists on SD card.

**Comment by AlexandraTrifan** [comment]
Tracking the issue on JSON mismatch here: https://github.com/analogdevicesinc/adi-kuiper-imager/issues/33

**Comment by tagoylo** [comment]
As per checking on the 2021R1 image Kuiper json and project list, they are matched now. But unable to fully test item 3 on the issue, due to #40.

**Comment by tagoylo** [comment]
Closing this item as it is no longer reproducible in RC3.
