### ISSUE TITLE
Update error message when Configuring Existing content of Kuiper Image with no kuiper.json offline

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/adi-kuiper-imager#31]
**Environment:**

OS: Windows 10
SW Version: v1.0.0-rc1 https://github.com/analogdevicesinc/adi-kuiper-imager/commit/217014db6e60b4a75bb6ddb68a1381387bb021e3

**Describe the bug:**
Setup:
Image written in SD card: Kuiper Image with no kuiper.json like 07-28 image or 2019R2
Internet connection: No internet connection 

With the given setup, trying to Configure Existing Content would not work since the image is not kuiper.json supported. But Configure Existing Content is still clickable but it throws an error popup that only says "fail", see photo below.
<img src="https://user-images.githubusercontent.com/25096080/202354015-4e8e352f-d946-46e0-8660-114bfa5fd260.png" width=50% height=50%>

**Expected Behavior:**
It would be nice to update the error message to be more specific as to why the feature is an error or why it says "fail". Maybe like "Kuiper Linux version has no kuiper.json. This will not work offline." or something.

**Comment by AlexandraTrifan** [comment]
This issue is has the same root cause as #24. 
I created an issue that will contain all these related issues- can be tracked here: https://github.com/analogdevicesinc/adi-kuiper-imager/issues/34

**Comment by tagoylo** [comment]
Message is now updated in RC2. But it only appears when clicking target platform.

This is the screenshot when selecting Configure Existing Content even if there is no Kuiper.json in SD card. Should the warning be different if there is no Kuiper.json in SD card?

![Screenshot 2023-02-15 at 4 55 27 PM](https://user-images.githubusercontent.com/25096080/218982314-344a8e36-3ed6-4df1-9c36-305c28077e73.png)

Then, this is what happens after clicking a target platform.
![Screenshot 2023-02-15 at 4 59 41 PM](https://user-images.githubusercontent.com/25096080/218982331-2c84f76a-0491-47db-bc61-fc904990cfa0.png)
