### ISSUE TITLE
JSON files need updating on swdownloads.

### ISSUE THREAD

**Issue by AlexandraTrifan** [analogdevicesinc/adi-kuiper-imager#33]
All the kuiper.json files for the supported kuiper versions should be copied to swdownloads from the boot partition.

**Comment by AlexandraTrifan** [comment]
All the JSON files related to the Kuiper Imager were updated to match official releases.

**Comment by tagoylo** [comment]
While checking for the kuiper json swdownloads path defined [here](https://swdownloads.analog.com/cse/kuiper/imager/kuiper_os_list.json), it returns none and seems to be empty.

**Comment by AlexandraTrifan** [comment]
Renamed the mismatching file, can you check again?
